// src/solid/screens/CampaignView.tsx
/**
 * CampaignView — SolidJS campaign progression screen (US-F03).
 *
 * Shows 16 missions organized by 4 chapters of 4 missions each.
 * Completed missions show star rating, locked missions show padlock.
 * Clicking an unlocked mission navigates to the briefing screen.
 */

import { type Component, createMemo, For, Show } from "solid-js";
import { CAMPAIGN } from "@/entities/missions";
import type { MissionDef } from "@/entities/types";
import type { AppState } from "../appState";

/** Chapter labels for the 4 chapters. */
const CHAPTER_NAMES = ["First Landing", "Deep Operations", "Turning Tide", "Final Offensive"];

type MissionStatus = "locked" | "available" | "completed";

interface MissionSlot {
	def: MissionDef;
	status: MissionStatus;
	stars: number;
}

interface ChapterGroup {
	chapter: number;
	name: string;
	missions: MissionSlot[];
}

/**
 * Determine mission status based on campaign progress.
 * For now, mission 1 is always available; subsequent missions are available
 * if the previous mission is completed. In the full version, this would
 * read from persisted campaign progress.
 */
function getMissionSlots(): MissionSlot[] {
	return CAMPAIGN.map((def, index) => {
		// First mission always available, rest locked until wired to persistence
		const status: MissionStatus = index === 0 ? "available" : "locked";
		return { def, status, stars: 0 };
	});
}

/** Group missions into 4 chapters of 4 missions each. */
function getChapters(slots: MissionSlot[]): ChapterGroup[] {
	const chapters: ChapterGroup[] = [];
	for (let c = 1; c <= 4; c++) {
		chapters.push({
			chapter: c,
			name: CHAPTER_NAMES[c - 1],
			missions: slots.filter((s) => s.def.chapter === c),
		});
	}
	return chapters;
}

/** Star rating display. */
const StarRating: Component<{ stars: number }> = (props) => {
	return (
		<div class="flex gap-0.5 text-xs">
			<For each={[1, 2, 3]}>
				{(i) => (
					<span
						class={
							i <= props.stars
								? props.stars === 3
									? "text-yellow-400"
									: props.stars === 2
										? "text-gray-300"
										: "text-amber-600"
								: "text-slate-600"
						}
					>
						{i <= props.stars ? "\u2605" : "\u2606"}
					</span>
				)}
			</For>
		</div>
	);
};

/** Individual mission card. */
const MissionCard: Component<{
	slot: MissionSlot;
	onClick: () => void;
}> = (props) => {
	const isLocked = () => props.slot.status === "locked";
	const isCompleted = () => props.slot.status === "completed";

	return (
		<button
			type="button"
			disabled={isLocked()}
			onClick={props.onClick}
			class={`group relative rounded-md border px-3 py-3 text-left transition ${
				isLocked()
					? "cursor-not-allowed border-slate-700/40 bg-slate-900/15 opacity-50"
					: isCompleted()
						? "border-primary/35 bg-primary/8 hover:border-primary/55 hover:bg-primary/12"
						: "border-accent/30 bg-slate-900/30 hover:border-accent/55 hover:bg-slate-900/45"
			}`}
		>
			<div class="flex items-start justify-between gap-2">
				<div class="min-w-0 flex-1">
					<div class="font-mono text-[9px] uppercase tracking-[0.22em] text-slate-500">
						{props.slot.def.chapter}-{props.slot.def.mission}
					</div>
					<div
						class={`mt-0.5 font-heading text-sm uppercase tracking-[0.14em] ${
							isLocked() ? "text-slate-500" : "text-slate-100"
						}`}
					>
						{props.slot.def.name}
					</div>
					<div class="mt-1 line-clamp-1 font-body text-[10px] uppercase tracking-[0.1em] text-slate-500">
						{props.slot.def.subtitle}
					</div>
				</div>
				<div class="flex shrink-0 flex-col items-end gap-1">
					<Show when={isLocked()}>
						<span role="img" class="font-mono text-sm text-slate-600" aria-label="Locked">
							&#x1F512;
						</span>
					</Show>
					<Show when={isCompleted()}>
						<StarRating stars={props.slot.stars} />
					</Show>
					<Show when={!isLocked() && !isCompleted()}>
						<span class="rounded border border-accent/25 bg-accent/10 px-1.5 py-0.5 font-mono text-[8px] uppercase tracking-[0.2em] text-accent">
							Available
						</span>
					</Show>
				</div>
			</div>
		</button>
	);
};

export const CampaignView: Component<{ app: AppState }> = (props) => {
	const slots = createMemo(() => getMissionSlots());
	const chapters = createMemo(() => getChapters(slots()));
	const completedCount = createMemo(() => slots().filter((s) => s.status === "completed").length);

	const handleMissionClick = (missionId: string) => {
		const slot = slots().find((s) => s.def.id === missionId);
		if (!slot || slot.status === "locked") return;
		props.app.setCurrentMissionId(missionId);
		props.app.setScreen("briefing");
	};

	return (
		<div class="flex min-h-screen w-screen flex-col items-center bg-slate-950 text-slate-100">
			<div class="relative z-10 flex w-full max-w-4xl flex-col gap-6 px-4 py-8">
				{/* Header */}
				<div class="flex flex-col items-center gap-2 text-center">
					<div class="inline-block border border-accent/25 bg-accent/10 px-3 py-1 font-mono text-[10px] uppercase tracking-[0.28em] text-accent">
						Copper-Silt Reach
					</div>
					<h2 class="font-heading text-2xl uppercase tracking-[0.22em] text-primary">Campaign</h2>
					<p class="font-mono text-[10px] uppercase tracking-[0.14em] text-slate-400">
						{completedCount()} of {CAMPAIGN.length} missions completed
					</p>
				</div>

				{/* Mission chapters */}
				<div class="grid gap-6">
					<For each={chapters()}>
						{(chapter) => (
							<div>
								<div class="mb-3 flex items-center gap-2">
									<span class="rounded border border-accent/20 bg-accent/8 px-2 py-0.5 font-mono text-[9px] uppercase tracking-[0.24em] text-accent">
										Chapter {chapter.chapter}
									</span>
									<span class="font-heading text-sm uppercase tracking-[0.16em] text-slate-100">
										{chapter.name}
									</span>
								</div>
								<div class="grid gap-2 sm:grid-cols-2 lg:grid-cols-4">
									<For each={chapter.missions}>
										{(slot) => (
											<MissionCard slot={slot} onClick={() => handleMissionClick(slot.def.id)} />
										)}
									</For>
								</div>
							</div>
						)}
					</For>
				</div>

				{/* Back button */}
				<div class="flex justify-center">
					<button
						type="button"
						class="min-h-11 rounded border border-slate-600/70 bg-slate-900/85 px-6 py-2 font-mono text-xs uppercase tracking-[0.18em] text-slate-100 backdrop-blur-sm transition-colors hover:border-accent/50 hover:bg-slate-800/85"
						onClick={() => props.app.setScreen("main-menu")}
					>
						Back to Menu
					</button>
				</div>
			</div>
		</div>
	);
};

// src/ui/command-post/CampaignView.tsx
/**
 * CampaignView — Campaign progression UI (US-050 + US-051).
 *
 * Shows 16 missions organized by 4 chapters of 4 missions each.
 * Completed missions show star rating (bronze/silver/gold).
 * Locked missions are greyed out with padlock indicator.
 * Clicking an unlocked mission navigates to the briefing screen.
 *
 * Difficulty selection is integrated: New Game picks difficulty,
 * and difficulty cannot be lowered mid-campaign (US-051).
 */

import { useTrait, useWorld } from "koota/react";
import { useMemo, useState } from "react";
import { Button } from "@/components/ui/button";
import { AppScreen, CampaignProgress } from "@/ecs/traits/state";
import { CAMPAIGN } from "@/entities/missions";
import type { MissionDef } from "@/entities/types";
import { type DifficultyId, getDifficultyDef } from "@/game/difficulty";
import { CommandPostShell } from "@/ui/layout/shells";
import { cn } from "@/ui/lib/utils";

/** Chapter labels for the 4 chapters. */
const CHAPTER_NAMES = ["First Landing", "Deep Operations", "Turning Tide", "Final Offensive"];

type MissionStatus = "locked" | "available" | "completed";

interface MissionSlot {
	def: MissionDef;
	status: MissionStatus;
	stars: number;
}

function getMissionStatus(
	missionDef: MissionDef,
	missions: Record<string, { status: string; stars: number; bestTime: number }>,
	campaignIndex: number,
): { status: MissionStatus; stars: number } {
	const entry = missions[missionDef.id];
	if (entry?.status === "completed") {
		return { status: "completed", stars: entry.stars };
	}

	// First mission is always available
	if (campaignIndex === 0) {
		return { status: "available", stars: 0 };
	}

	// Available if previous mission is completed
	const prevMission = CAMPAIGN[campaignIndex - 1];
	if (prevMission && missions[prevMission.id]?.status === "completed") {
		return { status: "available", stars: 0 };
	}

	return { status: "locked", stars: 0 };
}

function StarRating({ stars, size = "md" }: { stars: number; size?: "sm" | "md" }) {
	const starSize = size === "sm" ? "text-xs" : "text-base";
	return (
		<div className={cn("flex gap-0.5", starSize)} data-testid="star-rating">
			{[1, 2, 3].map((i) => (
				<span
					key={i}
					className={cn(
						i <= stars
							? stars === 3
								? "text-yellow-400" // gold
								: stars === 2
									? "text-gray-300" // silver
									: "text-amber-600" // bronze
							: "text-muted-foreground/30",
					)}
				>
					{i <= stars ? "\u2605" : "\u2606"}
				</span>
			))}
		</div>
	);
}

function MissionCard({ slot, onClick }: { slot: MissionSlot; onClick: () => void }) {
	const isLocked = slot.status === "locked";
	const isCompleted = slot.status === "completed";

	return (
		<button
			type="button"
			data-testid={`mission-card-${slot.def.id}`}
			disabled={isLocked}
			onClick={onClick}
			className={cn(
				"group relative rounded-md border px-3 py-3 text-left transition",
				isLocked
					? "cursor-not-allowed border-border/40 bg-background/15 opacity-50"
					: isCompleted
						? "border-primary/35 bg-primary/8 hover:border-primary/55 hover:bg-primary/12"
						: "border-accent/30 bg-background/30 hover:border-accent/55 hover:bg-background/45",
			)}
		>
			<div className="flex items-start justify-between gap-2">
				<div className="min-w-0 flex-1">
					<div className="font-mono text-[9px] uppercase tracking-[0.22em] text-muted-foreground">
						{slot.def.chapter}-{slot.def.mission}
					</div>
					<div
						className={cn(
							"mt-0.5 font-heading text-sm uppercase tracking-[0.14em]",
							isLocked ? "text-muted-foreground" : "text-foreground",
						)}
					>
						{slot.def.name}
					</div>
					<div className="mt-1 font-body text-[10px] uppercase tracking-[0.1em] text-muted-foreground line-clamp-1">
						{slot.def.subtitle}
					</div>
				</div>
				<div className="flex shrink-0 flex-col items-end gap-1">
					{isLocked ? (
						<span
							role="img"
							className="font-mono text-sm text-muted-foreground/50"
							aria-label="Locked"
							data-testid={`mission-locked-${slot.def.id}`}
						>
							&#x1F512;
						</span>
					) : isCompleted ? (
						<StarRating stars={slot.stars} size="sm" />
					) : (
						<span className="rounded border border-accent/25 bg-accent/10 px-1.5 py-0.5 font-mono text-[8px] uppercase tracking-[0.2em] text-accent">
							Available
						</span>
					)}
				</div>
			</div>
		</button>
	);
}

export function CampaignView() {
	const world = useWorld();
	const campaign = useTrait(world, CampaignProgress);
	const missions = campaign?.missions ?? {};
	const currentDifficulty = (campaign?.difficulty ?? "support") as DifficultyId;
	// Reserved for future mission detail panel
	const [_selectedMissionId, _setSelectedMissionId] = useState<string | null>(null);

	const slots = useMemo<MissionSlot[]>(
		() =>
			CAMPAIGN.map((def, index) => {
				const { status, stars } = getMissionStatus(def, missions, index);
				return { def, status, stars };
			}),
		[missions],
	);

	/** Group missions by chapter (4 chapters x 4 missions). */
	const chapters = useMemo(() => {
		const grouped: { chapter: number; name: string; missions: MissionSlot[] }[] = [];
		for (let c = 1; c <= 4; c++) {
			grouped.push({
				chapter: c,
				name: CHAPTER_NAMES[c - 1],
				missions: slots.filter((s) => s.def.chapter === c),
			});
		}
		return grouped;
	}, [slots]);

	const completedCount = slots.filter((s) => s.status === "completed").length;

	const handleMissionClick = (missionId: string) => {
		const slot = slots.find((s) => s.def.id === missionId);
		if (!slot || slot.status === "locked") return;

		// Set current mission and navigate to game (which shows briefing via CommandConsole)
		if (!campaign) return;
		world.set(CampaignProgress, {
			...campaign,
			currentMission: missionId,
		});
		world.set(AppScreen, { screen: "game" });
	};

	return (
		<CommandPostShell
			title="Campaign"
			subtitle={`${completedCount} of ${CAMPAIGN.length} missions completed`}
			eyebrow="Copper-Silt Reach"
			meta={
				<div className="flex items-center gap-2">
					<span className="font-mono text-[10px] uppercase tracking-[0.2em] text-muted-foreground">
						Difficulty:
					</span>
					<span className="rounded border border-accent/25 bg-accent/10 px-2 py-1 font-mono text-[10px] uppercase tracking-[0.22em] text-accent">
						{getDifficultyDef(currentDifficulty).label}
					</span>
				</div>
			}
			footer={
				<div className="flex flex-wrap gap-2">
					<Button variant="command" onClick={() => world.set(AppScreen, { screen: "menu" })}>
						Back to Menu
					</Button>
				</div>
			}
		>
			<div className="grid gap-6" data-testid="campaign-view">
				{chapters.map((chapter) => (
					<div key={chapter.chapter}>
						<div className="mb-3 flex items-center gap-2">
							<span className="rounded border border-accent/20 bg-accent/8 px-2 py-0.5 font-mono text-[9px] uppercase tracking-[0.24em] text-accent">
								Chapter {chapter.chapter}
							</span>
							<span className="font-heading text-sm uppercase tracking-[0.16em] text-foreground">
								{chapter.name}
							</span>
						</div>
						<div className="grid gap-2 sm:grid-cols-2 lg:grid-cols-4">
							{chapter.missions.map((slot) => (
								<MissionCard
									key={slot.def.id}
									slot={slot}
									onClick={() => handleMissionClick(slot.def.id)}
								/>
							))}
						</div>
					</div>
				))}
			</div>
		</CommandPostShell>
	);
}
