// src/ui/hud/TransmissionPortrait.tsx
import { useEffect, useMemo, useState } from "react";
import { cn } from "@/ui/lib/utils";

interface AtlasFrame {
	frame: { x: number; y: number; w: number; h: number };
	sourceSize: { w: number; h: number };
}

interface PortraitAtlas {
	meta: { image: string; size: { w: number; h: number }; scale: number };
	frames: Record<string, AtlasFrame>;
}

let portraitAtlasPromise: Promise<PortraitAtlas> | null = null;

function loadPortraitAtlas() {
	if (!portraitAtlasPromise) {
		portraitAtlasPromise = fetch("/assets/portraits/portraits_3x.json").then((response) => {
			if (!response.ok) {
				throw new Error(`Failed to load portrait atlas: ${response.status}`);
			}
			return response.json() as Promise<PortraitAtlas>;
		});
	}

	return portraitAtlasPromise;
}

function toInitials(label: string) {
	return label
		.replace(/_/g, " ")
		.split(/\s+/)
		.map((part) => part[0]?.toUpperCase() ?? "")
		.join("")
		.slice(0, 3);
}

export function TransmissionPortrait({
	portraitId,
	speaker,
	compact,
	className,
}: {
	portraitId?: string | null;
	speaker: string;
	compact?: boolean;
	className?: string;
}) {
	const [atlas, setAtlas] = useState<PortraitAtlas | null>(null);

	useEffect(() => {
		let cancelled = false;
		loadPortraitAtlas()
			.then((data) => {
				if (!cancelled) setAtlas(data);
			})
			.catch(() => {
				if (!cancelled) setAtlas(null);
			});

		return () => {
			cancelled = true;
		};
	}, []);

	const label = (portraitId ?? speaker).replace(/_/g, " ").toUpperCase();
	const portraitFrame =
		(portraitId ? atlas?.frames[portraitId] : null) ??
		(portraitId ? atlas?.frames[`${portraitId}_idle_0`] : null) ??
		null;
	const targetWidth = compact ? 72 : 92;
	const spriteStyle = useMemo(() => {
		if (!atlas || !portraitFrame) return null;
		const displayScale = targetWidth / portraitFrame.frame.w;
		return {
			backgroundImage: `url(/assets/portraits/${atlas.meta.image})`,
			backgroundPosition: `-${portraitFrame.frame.x * displayScale}px -${portraitFrame.frame.y * displayScale}px`,
			backgroundSize: `${atlas.meta.size.w * displayScale}px ${atlas.meta.size.h * displayScale}px`,
			width: `${targetWidth}px`,
			height: `${portraitFrame.frame.h * displayScale}px`,
			imageRendering: "pixelated" as const,
		};
	}, [atlas, portraitFrame, targetWidth]);

	return (
		<div
			data-testid="transmission-portrait"
			className={cn(
				"relative overflow-hidden rounded-md border border-accent/18 bg-[linear-gradient(180deg,rgba(19,20,17,0.94),rgba(8,11,10,0.98))]",
				className,
			)}
		>
			<div className="absolute inset-0 bg-[repeating-linear-gradient(180deg,rgba(255,255,255,0.03)_0,rgba(255,255,255,0.03)_1px,transparent_1px,transparent_5px)] opacity-30" />
			<div className={cn("relative grid gap-2 p-2", compact ? "w-22" : "w-27")}>
				<div className="font-mono text-[9px] uppercase tracking-[0.22em] text-muted-foreground">
					CO Feed
				</div>
				<div className="relative overflow-hidden rounded border border-accent/20 bg-[radial-gradient(circle_at_top,rgba(212,165,116,0.22),rgba(0,0,0,0.06))]">
					{portraitFrame && spriteStyle ? (
						<div
							role="img"
							aria-label={`${speaker} portrait`}
							className="mx-auto bg-no-repeat"
							style={spriteStyle}
						/>
					) : (
						<div
							role="img"
							aria-label={`${speaker} portrait`}
							className={cn(
								"flex items-center justify-center font-heading uppercase tracking-[0.24em] text-muted-foreground/70",
								compact ? "h-27 text-lg" : "h-34 text-xl",
							)}
						>
							{toInitials(label)}
						</div>
					)}
				</div>
				<div className="border-t border-border/60 pt-2 font-mono text-[9px] uppercase tracking-[0.18em] text-accent/85">
					{label}
				</div>
			</div>
		</div>
	);
}

// src/solid/hud/TransmissionPortrait.tsx
/**
 * TransmissionPortrait -- Character portrait from sprite atlas.
 *
 * Renders the portrait for Col. Bubbles, FOXHOUND, or Gen. Whiskers
 * in the command transmission panel. Loads portrait atlas JSON,
 * resolves frame coordinates, and displays from the sprite sheet
 * with pixelated rendering for the pixel art aesthetic.
 *
 * Falls back to speaker initials if the atlas or frame is unavailable.
 */

import { type Component, createMemo, createSignal, type JSX, onMount, Show } from "solid-js";

interface AtlasFrame {
	frame: { x: number; y: number; w: number; h: number };
	sourceSize: { w: number; h: number };
}

interface PortraitAtlas {
	meta: { image: string; size: { w: number; h: number }; scale: number };
	frames: Record<string, AtlasFrame>;
}

let portraitAtlasPromise: Promise<PortraitAtlas> | null = null;

function loadPortraitAtlas(): Promise<PortraitAtlas> {
	if (!portraitAtlasPromise) {
		portraitAtlasPromise = fetch(
			`${import.meta.env.BASE_URL}assets/portraits/portraits_3x.json`,
		).then((response) => {
			if (!response.ok) {
				throw new Error(`Failed to load portrait atlas: ${response.status}`);
			}
			return response.json() as Promise<PortraitAtlas>;
		});
	}
	return portraitAtlasPromise;
}

function toInitials(label: string): string {
	return label
		.replace(/_/g, " ")
		.split(/\s+/)
		.map((part) => part[0]?.toUpperCase() ?? "")
		.join("")
		.slice(0, 3);
}

export const TransmissionPortrait: Component<{
	/** Portrait frame ID in the atlas (e.g. "col_bubbles") */
	portraitId?: string | null;
	/** Speaker name for label display and fallback initials */
	speaker: string;
	/** Compact mode for smaller panels */
	compact?: boolean;
	/** Extra CSS classes */
	class?: string;
}> = (props) => {
	const [atlas, setAtlas] = createSignal<PortraitAtlas | null>(null);

	onMount(() => {
		loadPortraitAtlas()
			.then((data) => setAtlas(data))
			.catch(() => setAtlas(null));
	});

	const label = createMemo(() =>
		(props.portraitId ?? props.speaker).replace(/_/g, " ").toUpperCase(),
	);

	const portraitFrame = createMemo((): AtlasFrame | null => {
		const a = atlas();
		const pid = props.portraitId;
		if (!a || !pid) return null;
		return a.frames[pid] ?? a.frames[`${pid}_idle_0`] ?? null;
	});

	const targetWidth = createMemo(() => (props.compact ? 72 : 92));

	const spriteStyle = createMemo((): JSX.CSSProperties | null => {
		const a = atlas();
		const frame = portraitFrame();
		if (!a || !frame) return null;

		const displayScale = targetWidth() / frame.frame.w;
		return {
			"background-image": `url(${import.meta.env.BASE_URL}assets/portraits/${a.meta.image})`,
			"background-position": `-${frame.frame.x * displayScale}px -${frame.frame.y * displayScale}px`,
			"background-size": `${a.meta.size.w * displayScale}px ${a.meta.size.h * displayScale}px`,
			width: `${targetWidth()}px`,
			height: `${frame.frame.h * displayScale}px`,
			"image-rendering": "pixelated",
			"background-repeat": "no-repeat",
		};
	});

	return (
		<div
			data-testid="transmission-portrait"
			class={`relative overflow-hidden rounded-[2px] border border-green-500/18 bg-[linear-gradient(180deg,rgba(19,20,17,0.94),rgba(8,11,10,0.98))] ${props.class ?? ""}`}
		>
			{/* Scanline overlay */}
			<div
				aria-hidden="true"
				class="absolute inset-0 bg-[repeating-linear-gradient(180deg,rgba(255,255,255,0.03)_0,rgba(255,255,255,0.03)_1px,transparent_1px,transparent_5px)] opacity-30"
			/>

			<div class={`relative grid gap-2 p-2 ${props.compact ? "w-[88px]" : "w-[108px]"}`}>
				{/* Label */}
				<div class="font-mono text-[9px] uppercase tracking-[0.22em] text-slate-500">CO Feed</div>

				{/* Portrait frame */}
				<div class="relative overflow-hidden rounded-[1px] border border-green-500/20 bg-[radial-gradient(circle_at_top,rgba(212,165,116,0.22),rgba(0,0,0,0.06))]">
					<Show
						when={spriteStyle()}
						fallback={
							<div
								role="img"
								aria-label={`${props.speaker} portrait`}
								class={`flex items-center justify-center font-heading uppercase tracking-[0.24em] text-slate-600 ${
									props.compact ? "h-[108px] text-lg" : "h-[136px] text-xl"
								}`}
							>
								{toInitials(label())}
							</div>
						}
					>
						{(style) => (
							<div
								role="img"
								aria-label={`${props.speaker} portrait`}
								class="mx-auto"
								style={style()}
							/>
						)}
					</Show>
				</div>

				{/* Speaker name */}
				<div class="border-t border-slate-600/60 pt-2 font-mono text-[9px] uppercase tracking-[0.18em] text-green-400/85">
					{label()}
				</div>
			</div>
		</div>
	);
};
