// src/solid/mobile/RadialMenu.tsx
/**
 * RadialMenu — Radial context menu for long-press on mobile (SolidJS).
 *
 * Appears on long-press of a unit or ground position. Shows available
 * actions as pie segments arranged in a semicircle above the press point.
 * Uses createSignal for open/close state and position tracking.
 *
 * US-060: Long-press triggers radial command menu.
 * US-061: Touch-friendly with 48px+ hit areas.
 */

import { type Component, For, Show } from "solid-js";
import { DEFAULT_RADIAL_ACTIONS, type RadialAction, type RadialMenuState } from "./radialMenuState";

export type { RadialAction, RadialMenuState } from "./radialMenuState";
// Re-export state and types from the pure-TS module
export { createRadialMenuState, DEFAULT_RADIAL_ACTIONS } from "./radialMenuState";

const RADIAL_RADIUS = 80;

export const RadialMenu: Component<{
	actions?: RadialAction[];
	state: RadialMenuState;
	onAction: (actionId: string) => void;
}> = (props) => {
	const actions = () => props.actions ?? DEFAULT_RADIAL_ACTIONS;

	const handleAction = (actionId: string) => {
		props.onAction(actionId);
		props.state.close();
	};

	const handleBackdropClick = () => {
		props.state.close();
	};

	return (
		<Show when={props.state.open()}>
			{/* Full-screen dismiss backdrop */}
			<button
				type="button"
				data-testid="radial-menu"
				class="fixed inset-0 z-50 cursor-default bg-transparent"
				onClick={handleBackdropClick}
				onKeyDown={(e) => {
					if (e.key === "Escape") handleBackdropClick();
				}}
			>
				{/* Radial action segments */}
				<div
					class="absolute"
					style={{
						left: `${props.state.position().x}px`,
						top: `${props.state.position().y}px`,
					}}
				>
					<For each={actions()}>
						{(action, index) => {
							const angle = () => {
								const count = actions().length;
								const step = Math.PI / Math.max(count - 1, 1);
								return Math.PI + index() * step;
							};
							const x = () => Math.cos(angle()) * RADIAL_RADIUS;
							const y = () => Math.sin(angle()) * RADIAL_RADIUS;

							return (
								<button
									type="button"
									data-testid={`radial-${action.id}`}
									onClick={(e) => {
										e.stopPropagation();
										handleAction(action.id);
									}}
									class="absolute flex min-h-[48px] min-w-[48px] -translate-x-1/2 -translate-y-1/2 items-center justify-center rounded-none border-2 border-slate-500/50 bg-slate-900/90 px-3 shadow-[0_4px_12px_rgba(0,0,0,0.4)] font-mono text-[10px] uppercase tracking-[0.18em] text-slate-100 active:border-green-500/60 active:bg-slate-800/90"
									style={{
										left: `${x()}px`,
										top: `${y()}px`,
									}}
								>
									{action.label}
								</button>
							);
						}}
					</For>
				</div>
			</button>
		</Show>
	);
};

// src/ui/mobile/RadialMenu.tsx
/**
 * RadialMenu — Mobile context radial menu (long-press).
 *
 * US-060: Long-press triggers radial command menu after 500ms.
 * Actions fan out in a semicircle above the press point.
 * Touch-friendly with 48px+ hit areas (exceeds 44px minimum from US-061).
 *
 * Ground long-press actions: Move, Attack-Move, Patrol, Rally
 * Unit long-press actions: unit-specific options
 */
import type { ReactNode } from "react";
import { cn } from "@/ui/lib/utils";

interface RadialAction {
	id: string;
	label: string;
}

interface RadialMenuProps {
	actions: RadialAction[];
	open: boolean;
	position: { x: number; y: number };
	onAction: (id: string) => void;
	onClose: () => void;
}

/** Default ground actions for US-060 radial menu. */
export const GROUND_RADIAL_ACTIONS: RadialAction[] = [
	{ id: "move", label: "Move" },
	{ id: "attack-move", label: "Atk Move" },
	{ id: "patrol", label: "Patrol" },
	{ id: "rally", label: "Rally" },
];

/** Default unit actions for US-060 radial menu. */
export const UNIT_RADIAL_ACTIONS: RadialAction[] = [
	{ id: "move", label: "Move" },
	{ id: "stop", label: "Stop" },
	{ id: "attack", label: "Attack" },
	{ id: "hold", label: "Hold" },
];

export function RadialMenu({ actions, open, position, onAction, onClose }: RadialMenuProps) {
	if (!open) return null;

	const angleStep = Math.PI / Math.max(actions.length - 1, 1);
	const radius = 72;

	return (
		<RadialBackdrop onClose={onClose}>
			<div className="absolute" style={{ left: position.x, top: position.y }}>
				{actions.map((action, i) => {
					const angle = Math.PI + i * angleStep;
					const x = Math.cos(angle) * radius;
					const y = Math.sin(angle) * radius;

					return (
						<button
							key={action.id}
							type="button"
							onClick={(e) => {
								e.stopPropagation();
								onAction(action.id);
							}}
							className={cn(
								"absolute flex min-h-[48px] min-w-[48px] -translate-x-1/2 -translate-y-1/2",
								"items-center justify-center rounded-none px-2",
								"border-2 border-border bg-card shadow-[0_4px_12px_rgba(0,0,0,0.3)]",
								"font-heading text-[9px] uppercase tracking-wider text-card-foreground",
								"active:border-accent active:text-accent",
							)}
							style={{
								left: x,
								top: y,
							}}
						>
							{action.label}
						</button>
					);
				})}
			</div>
		</RadialBackdrop>
	);
}

/** Full-screen dismiss backdrop for the radial menu. */
function RadialBackdrop({ onClose, children }: { onClose: () => void; children: ReactNode }) {
	return (
		<button
			type="button"
			data-testid="radial-menu"
			className="fixed inset-0 z-50 cursor-default bg-transparent"
			onClick={onClose}
		>
			{children}
		</button>
	);
}
