// src/solid/hud/AlertBanner.tsx
/**
 * AlertBanner — Top-right alert notifications for gameplay events.
 *
 * Shows the last 3 tactical alerts, color-coded by severity:
 * info = cyan, warning = amber, critical = rose.
 * Clicking an alert with a world position emits focusCamera to snap the camera.
 * Alerts auto-dismiss after 3 seconds via setTimeout in onMount.
 * Slide-in animation via CSS transition.
 *
 * Reads from solidBridge alerts store + emits camera-focus commands.
 */

import { type Component, createMemo, For, onCleanup, onMount, Show } from "solid-js";
import type {
	AlertViewModel,
	SolidBridgeAccessors,
	SolidBridgeEmit,
} from "@/engine/bridge/solidBridge";

const MAX_VISIBLE = 3;
const ALERT_DISMISS_MS = 3000;

const SEVERITY_STYLES: Record<AlertViewModel["severity"], string> = {
	info: "border-cyan-500/50 bg-cyan-950/20 text-cyan-300",
	warning: "border-amber-500/50 bg-amber-950/20 text-amber-300",
	critical: "border-rose-500/50 bg-rose-950/20 text-rose-300",
};

const BADGE_STYLES: Record<AlertViewModel["severity"], string> = {
	info: "border-cyan-500/30 bg-cyan-500/10 text-cyan-400",
	warning: "border-amber-500/30 bg-amber-500/10 text-amber-400",
	critical: "border-rose-500/30 bg-rose-500/10 text-rose-400",
};

export const AlertBanner: Component<{ bridge: SolidBridgeAccessors; emit?: SolidBridgeEmit }> = (
	props,
) => {
	const visibleAlerts = createMemo(() => {
		const all = props.bridge.alerts;
		return all.slice(-MAX_VISIBLE);
	});

	// Auto-dismiss: set timers for each alert to dismiss after ALERT_DISMISS_MS
	const dismissTimers = new Map<string, ReturnType<typeof setTimeout>>();

	onMount(() => {
		// Watch for new alerts and set dismiss timers
		const checkInterval = window.setInterval(() => {
			const alerts = props.bridge.alerts;
			for (const alert of alerts) {
				if (!dismissTimers.has(alert.id)) {
					const timer = setTimeout(() => {
						props.emit?.dismissAlert(alert.id);
						dismissTimers.delete(alert.id);
					}, ALERT_DISMISS_MS);
					dismissTimers.set(alert.id, timer);
				}
			}
		}, 200);

		onCleanup(() => {
			window.clearInterval(checkInterval);
			for (const timer of dismissTimers.values()) {
				clearTimeout(timer);
			}
			dismissTimers.clear();
		});
	});

	function handleAlertClick(alert: AlertViewModel): void {
		if (alert.worldX !== undefined && alert.worldY !== undefined && props.emit) {
			props.emit.focusCamera(alert.worldX, alert.worldY);
		}
		props.emit?.dismissAlert(alert.id);
	}

	return (
		<div data-testid="alert-banner" class="flex w-full flex-col gap-2 sm:ml-auto sm:max-w-sm">
			<Show
				when={visibleAlerts().length > 0}
				fallback={
					<div class="border border-green-500/12 bg-slate-950/75 shadow-[0_16px_32px_rgba(0,0,0,0.28)]">
						<div class="flex items-center justify-between gap-2 p-3">
							<span class="rounded border border-green-500/25 bg-green-500/10 px-2 py-0.5 font-mono text-[10px] uppercase tracking-[0.22em] text-green-400">
								CLEAR
							</span>
							<span class="font-mono text-[10px] uppercase tracking-[0.22em] text-slate-400">
								No active alerts
							</span>
						</div>
					</div>
				}
			>
				<For each={visibleAlerts()}>
					{(alert) => (
						<button
							type="button"
							class={`w-full cursor-pointer text-left font-mono text-xs uppercase tracking-wider shadow-[0_18px_36px_rgba(0,0,0,0.3)] transition-all duration-300 ease-out animate-slide-in-right hover:opacity-90 border ${SEVERITY_STYLES[alert.severity]}`}
							onClick={() => handleAlertClick(alert)}
							title={
								alert.worldX !== undefined && alert.worldY !== undefined
									? "Click to focus camera"
									: undefined
							}
						>
							<div class="flex items-center gap-2 p-3">
								<span
									class={`rounded border px-2 py-0.5 text-[10px] uppercase tracking-[0.22em] ${BADGE_STYLES[alert.severity]}`}
								>
									{alert.severity}
								</span>
								<span class="flex-1">{alert.message}</span>
								<Show when={alert.worldX !== undefined && alert.worldY !== undefined}>
									<span class="text-[10px] opacity-60">[locate]</span>
								</Show>
							</div>
						</button>
					)}
				</For>
			</Show>
		</div>
	);
};

// src/ui/hud/AlertBanner.tsx
/**
 * AlertBanner — Top-right alert notifications for gameplay events.
 *
 * Displays ephemeral alert messages for key game events:
 * - "Under Attack!" when player units take damage from enemies
 * - "Building Complete" when construction finishes
 * - "Training Complete" when unit production finishes
 * - "Enemy Spotted" when fog reveals enemy units
 * - "Objective Complete" when mission objectives are achieved
 *
 * Alerts auto-dismiss after 3 seconds. Maximum 3 visible simultaneously.
 * Clicking an alert dispatches camera-center to the event location.
 *
 * US-016: AlertBanner event wiring
 */
import { useCallback, useEffect, useState } from "react";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent } from "@/components/ui/card";
import { EventBus } from "@/game/EventBus";
import { cn } from "@/ui/lib/utils";

const MAX_VISIBLE_ALERTS = 3;
const ALERT_DISMISS_MS = 3000;

export interface Alert {
	id: string;
	message: string;
	severity: "info" | "warning" | "critical";
	/** World position to center camera on when clicked */
	worldX?: number;
	worldY?: number;
}

export type AlertPayload = Omit<Alert, "id">;

/** Emit a HUD alert from any system or component. */
export function emitHudAlert(alert: AlertPayload) {
	EventBus.emit("hud-alert", alert);
}

export function AlertBanner() {
	const [alerts, setAlerts] = useState<Alert[]>([]);

	const push = useCallback((alert: AlertPayload) => {
		const id = `alert-${Date.now()}-${Math.random().toString(36).slice(2)}`;
		setAlerts((prev) => {
			// Keep only the last (MAX - 1) alerts + new one
			const trimmed = prev.slice(-(MAX_VISIBLE_ALERTS - 1));
			return [...trimmed, { ...alert, id }];
		});
		window.setTimeout(() => {
			setAlerts((prev) => prev.filter((a) => a.id !== id));
		}, ALERT_DISMISS_MS);
	}, []);

	useEffect(() => {
		const onHudAlert = (alert: AlertPayload) => push(alert);

		// Wire standard game events to alerts
		const onUnderAttack = (data?: { x?: number; y?: number }) =>
			push({
				message: "Under Attack!",
				severity: "critical",
				worldX: data?.x,
				worldY: data?.y,
			});

		const onBuildingComplete = (data?: { name?: string; x?: number; y?: number }) =>
			push({
				message: data?.name ? `${data.name} Complete` : "Building Complete",
				severity: "info",
				worldX: data?.x,
				worldY: data?.y,
			});

		const onTrainingComplete = (data?: { name?: string; x?: number; y?: number }) =>
			push({
				message: data?.name ? `${data.name} Ready` : "Training Complete",
				severity: "info",
				worldX: data?.x,
				worldY: data?.y,
			});

		const onEnemySpotted = (data?: { x?: number; y?: number }) =>
			push({
				message: "Enemy Spotted",
				severity: "warning",
				worldX: data?.x,
				worldY: data?.y,
			});

		const onObjectiveComplete = (data?: { description?: string }) =>
			push({
				message: data?.description
					? `Objective: ${data.description}`
					: "Objective Complete",
				severity: "info",
			});

		const onSceneReady = () =>
			push({ message: "Scene sync green", severity: "info" });

		const onMissionFailed = () =>
			push({ message: "Mission pressure spiking", severity: "critical" });

		EventBus.on("hud-alert", onHudAlert);
		EventBus.on("under-attack", onUnderAttack);
		EventBus.on("building-complete", onBuildingComplete);
		EventBus.on("training-complete", onTrainingComplete);
		EventBus.on("enemy-spotted", onEnemySpotted);
		EventBus.on("objective-complete", onObjectiveComplete);
		EventBus.on("current-scene-ready", onSceneReady);
		EventBus.on("mission-failed", onMissionFailed);

		return () => {
			EventBus.off("hud-alert", onHudAlert);
			EventBus.off("under-attack", onUnderAttack);
			EventBus.off("building-complete", onBuildingComplete);
			EventBus.off("training-complete", onTrainingComplete);
			EventBus.off("enemy-spotted", onEnemySpotted);
			EventBus.off("objective-complete", onObjectiveComplete);
			EventBus.off("current-scene-ready", onSceneReady);
			EventBus.off("mission-failed", onMissionFailed);
		};
	}, [push]);

	const handleAlertClick = useCallback((alert: Alert) => {
		if (alert.worldX !== undefined && alert.worldY !== undefined) {
			EventBus.emit("camera-center", { x: alert.worldX, y: alert.worldY });
		}
		setAlerts((prev) => prev.filter((a) => a.id !== alert.id));
	}, []);

	if (alerts.length === 0) {
		return (
			<Card
				data-testid="alert-banner"
				className="canvas-grain w-full border-accent/12 bg-card/75 shadow-[0_16px_32px_rgba(0,0,0,0.28)] sm:ml-auto sm:max-w-sm"
			>
				<CardContent className="flex items-center justify-between gap-2 p-3">
					<Badge variant="accent">CLEAR</Badge>
					<span className="font-mono text-[10px] uppercase tracking-[0.22em] text-muted-foreground">
						No active alerts
					</span>
				</CardContent>
			</Card>
		);
	}

	return (
		<div data-testid="alert-banner" className="flex w-full flex-col gap-2 sm:ml-auto sm:max-w-sm">
			{alerts.map((alert) => (
				<Card
					key={alert.id}
					className={cn(
						"canvas-grain cursor-pointer font-heading text-xs uppercase tracking-wider shadow-[0_18px_36px_rgba(0,0,0,0.3)] transition-opacity hover:opacity-90",
						alert.severity === "critical" &&
							"border-destructive bg-destructive/20 text-destructive",
						alert.severity === "warning" && "border-accent bg-accent/10 text-accent",
						alert.severity === "info" && "border-border bg-card text-card-foreground",
					)}
					onClick={() => handleAlertClick(alert)}
				>
					<CardContent className="flex items-center gap-2 p-3">
						<Badge
							variant={
								alert.severity === "critical"
									? "danger"
									: alert.severity === "warning"
										? "accent"
										: "default"
							}
						>
							{alert.severity}
						</Badge>
						<span>{alert.message}</span>
					</CardContent>
				</Card>
			))}
		</div>
	);
}
